### ISSUE TITLE
www and non-www issues

### ISSUE THREAD

**Issue by Bechrissed** [interbrite/letsencrypt-vesta#12]
Hi,

I have a problem generating the certificate for my server. In my vesta config I have multiple domain names. For the main domain I am having problems running your script.

I'm using the following command:

`letsencrypt-vesta admin domaina.nl domainb.nl domainc.nl`

which results in the following errors:

```
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/cert.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/privkey.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/chain.pem': No such file or directory
Error: /var/tmp/ssl-domaina.nl-1709/domaina.nl.crt not found
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/cert.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/privkey.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/chain.pem': No such file or directory
Error: /var/tmp/ssl-domaina.nl-1709/domainb.nl.crt not found
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/cert.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/privkey.pem': No such file or directory
cp: cannot stat '/etc/letsencrypt/live/domaina.nl/chain.pem': No such file or directory
Error: /var/tmp/ssl-domaina.nl-1709/domainc.nl.crt not found
```

When I look into the folder /etc/letsencrypt/live/ I see only www.domaina.nl and not domaina.nl which explains why your script can't find the certificates. So I thought the solution would be running the command with www. eg:

`letsencrypt-vesta admin www.domaina.nl domainb.nl domainc.nl`

But then the script won't run because it tells me www.domaina.nl is not part of my admin account in Vesta. And results in following error:

`Warning: www.domaina.nl does not exist in the admin account.`

Any ideas how to fix this? Is it an issue with your script or in my config?

**Comment by Bechrissed** [comment]
Well i've fixed it for now, by hardcoding 'www.' into the copy part of your script... :s

**Comment by gellenburg** [comment]
Hi.

I'm having the same problem. My problem is letsencrypt-vesta assumes that every domain has a www subdomain, but this isn't always the case.

I can't add a letsencrypt-vesta ssl certificate for one of my domains because it doesn't have a www subdomain:

`root@XXXXX:~# letsencrypt-vesta -u XXXXX files.XXXXX.org
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --no-self-upgrade -t --renew-by-default --agree-tos --webroot -w /etc/letsencrypt/webroot --server https://acme-v01.api.letsencrypt.org/directory -m XXXXX@XXXXX.org -d files.XXXXX.org,www.files.XXXXX.org certonly
Failed authorization procedure. www.files.XXXXX.org (http-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for www.files.XXXXX.org

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.files.XXXXX.org
   Type:   unknownHost
   Detail: No IPv4 addresses found for www.files.XXXXX.org

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
Let's encrypt returned an error status.  Aborting.`

But there is in fact an A record for the domain in question:

`root@XXXXX:~# nslookup files.XXXXX.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	files.XXXXX.org
Address: XXX.XXX.XXX.85
Name:	files.XXXXX.org
Address: XXX.XXX.XXX.85

root@XXXXX:~# `

The only solution has been to insert a www cname record into the domains' DNS which is something I really shouldn't be forced to do.

**Comment by jpitoniak** [comment]
Not sure why this would happen.  Could you attach a screen shot of the problematic domain's edit page (i.e. https://yourserver.tld:8083/edit/web/?domain=domaina.nl) so that I can try to recreate it with similar settings?

**Comment by gellenburg** [comment]
Found the problem.

Had to disable the web aliases that were being created automatically by 
Vesta:

v-delete-web-domain-alias [user] [domain] www.[domain]

Or more specifically:
v-delete-web-domain-alias [user] [domain] [domain-alias]

This issue can be closed.

**Comment by Bechrissed** [comment]
Sorry for the (very) late reply. It is the same issue as this currently open issue: https://github.com/interbrite/letsencrypt-vesta/issues/20 so I guess you can keep this issue closed. Any news if this will be possible in the near future?

**Comment by gellenburg** [comment]
It is possible today. Read my note from April 21. You need to delete the www domain alias that Vesta automatically creates (or subsequently add the www alias to your DNS).
