### ISSUE TITLE
[Feature suggestion] Add SSL on VestaCP panel

### ISSUE THREAD

**Issue by joubertredrat** [interbrite/letsencrypt-vesta#14]
Hi guys,
I'm looking here and on mine test was possible to put Let's encrypt SSL on VestaCP panel in port 8083.
Then, is possible to automate this with this script? I'm looking here if we can use the hostname for this or other variable.

**Comment by beatles1** [comment]
+1 to this. Loving the script, works perfectly for me so far. Would just be great if it could also do the panel itself on port 8083 as well.

**Comment by jpitoniak** [comment]
Thanks for your support.  I'm glad you find my tool useful.  I am not a VestaCP developer, but there is at least one feature request in the VestaCP bug queue requesting built-in support for Let's Encrypt, and it's marked "in progress." (https://bugs.vestacp.com/issues/67)

I wrote this tool because I wanted a quick way to manage my certs and I didn't want to invest the time into trying to learn to hack Vesta.  Integrating Let's Encrypt into Vesta, while similar in functionality, whole be drastically different in how it's coded.

I'd love to see an integrated solution, but that's outside the scope of this project, so I'm going to close this ticket.  If you really want to see integration, please add your feedback to the Vesta ticket linked above to encourage the developers over there to make that feature a priority.  In the meantime, please keep sharing your feedback, and I'll keep trying to make letsencrypt-vesta even better.
