### ISSUE TITLE
Problem with multiple subdomains

### ISSUE THREAD

**Issue by GestDPS** [interbrite/letsencrypt-vesta#3]
Hi !
There is a bug when i try to use multiple domains ( lets say exemple.tld and my.example.tld ) with two differents webroots, the script list all thé subdomains in the certificate request, but only install it on the main vhost. I'll send you my way using another script to resolve this hope you can correct it ;)

**Comment by jpitoniak** [comment]
So if I'm understanding you correctly, you want to use one certificate to cover all of the domain names hosted across an account, rather than just an individual site within that account, correct?  I designed the script to handle one certificate per site (with the possibility of multiple certificates per user), as that's the use case that I'm using personally, though I can see reasons why you might want to do it differently.

Let me think it over for a bit...I can probably change things up to make it work with both options.  I might take me a little while to get it done, though, as I go back to work tomorrow.  This project came about because I was off work for the holidays and had time to tinker.

**Comment by GestDPS** [comment]
The problèmes with doing one domain at a time, is that lets'encrypt will block you fast as their policy is 5 certificates per domain ( the 2nd level tld ) ... So you can be very fast blocked with initial certificates and renewals

**Comment by GestDPS** [comment]
5 certs / tld / week to ne precise

**Comment by jpitoniak** [comment]
Just to give you an update, I have a solution, I just need to test it before I feel comfortable releasing it.  I'll try to do that tomorrow and, if all goes well, I'll push out the update soon after.

**Comment by GestDPS** [comment]
If you want me to test it dont hesitate ;)

Le 11 janv. 2016 21:15, à 21:15, jpitoniak notifications@github.com a écrit:

**Comment by jpitoniak** [comment]
OK, the update has been committed. A "git pull origin master" in /usr/local/letsencrypt-vesta should get you the latest copy.

The new syntax lets you specify multiple users and/or sites per user.  The format is

```
-u username1 u1site1 u1site2 ... u1siteX ... -u usernameN uNsite1 uNsite2 ... uNsiteX
```

where `-u` indicates a new username and each username is optionally followed by a list of sites.  (If no sites are specified the script will every site under that account.)

Like before, you need only specify the main domain for each site and the script will include all of the aliases automatically.  For backwards compatibility, the first `-u` is optional.

Some examples:
- letsencrypt-vesta felines cat.domain.com (single site, works as before)
- letsencrypt-vesta -u felines cat.domain.com (same as above, new syntax)
- letsencrypt-vesta felines (create cert for every site in the felines account)
- letsencrypt-vesta felines cat.domain.com tiger.domain.com (create cert for cat and tiger sites in the felines account)
- letsencrypt-vesta felines cat.domain.com -u canines (create cert for cat.domain.com in felines account and all domains in the canines account)

Hopefully that meets your needs. :)
