### ISSUE TITLE
www shows invalid certificate on centos 7.2

### ISSUE THREAD

**Issue by rebootcode** [interbrite/letsencrypt-vesta#30]
Today, I installed letsencrypt-vesta . Everything installed fine.

But I just realised https://www.example.com shows invalid certificate, where https://example.com loads fine.

`www` shows invalid certicate.

I did get the error :- 

`
/usr/local/bin/letsencrypt-vesta: line 64: /usr/local/vesta/bin/v-list-web-domain-alias: No such file or directory
`

I am running on Centos 7.2 with vestacp 0.9.8.16

**Comment by jpitoniak** [comment]
This due to this issue: https://github.com/interbrite/letsencrypt-vesta/issues/27

In the most recent Vesta update the v-list-web-domains-alias command was removed, so letsencrypt-vesta is no longer able to get the alias list, in which the www variant of the URL is generally listed.  I need to do a little more research into what's going on before I can suggest a solution, though.

**Comment by byfoz** [comment]
Hi jpitoniak,

Just found this (untested as of yet) that seems to have a solution for your v-list-web-domains-alias command

https://forum.vestacp.com/viewtopic.php?t=11876

**Comment by jpitoniak** [comment]
@CImrie ,

Well, that command didn't exactly work for me (it returned the site's IP address, not a list of aliases), but v-list-web-domain does return aliases among other things, so I should be able to make it work.  I'll try to play with it tonight and see if I can get a release out soon.

Thanks!

**Comment by jpitoniak** [comment]
This should now be resolved after the update released on Saturday.  Please confirm.

**Comment by rebootcode** [comment]
It is resolved.

Thanks
