### ISSUE TITLE
renew certificates in batch

### ISSUE THREAD

**Issue by darkworks** [interbrite/letsencrypt-vesta#31]
in documentation we have 
`letsencrypt-vesta -a 60 USERNAME DOMAIN`

which mean if i have 5 domains i need to schedule at command differently 

so how about if we set 
`certbot-auto renew`

**Comment by jpitoniak** [comment]
Each time you call letsencrypt-vesta, you are requesting one certificate, regardless of how many domains you add to it.  When you use the -a option, you are simply scheduling the same command to run again in 60 days (or however many days you specify).  It will automatically renew the certificate, with all the domains attached to it, every 60 days.

The certbot "renew" command won't work with letsencrypt-vesta because letsencrypt-vesta copies the certificate files to where Vesta expects them to be, and Certbot doesn't know how to do that on renewal.  If you used "certbot-auto renew" on your server, you'd update the certificates inside /etc/letsencrypt, but your sites wouldn't be updated because they are pulling the certs from /home/USER/conf/web.

I had initially considered linking to the /etc/letsencrypt cert files to the paths that Vesta expects them to be at, but I instead decided to use Vesta's command line tools to do it to ensure that certificates are always put in the right place.  Presumably, if Vesta ever changes how sites are configured, they'll update the command line tools to match and letsencrypt-vesta will keep working, without any updates.

**Comment by darkworks** [comment]
ok thanks for update ...
